---
title: '191107'
author: "Yuqi Miao"
date: "11/7/2019"
output: html_document
---
```{r}
library(tidyverse)
# library(p8105.datasets)
set.seed(1)

```

# data manipulation

```{r}
nyc_airbnb = read_csv("nyc_airbnb.csv")

## mutate, rename, selection 

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood
  ) %>% 
  select(price, stars, boro, neighborhood, room_type)
  

```


# Fit a first model
```{r}
fit = lm(price~stars+boro, data = nyc_airbnb)

 ## the categoriacal variables are considered as different varibles? -- making different bicategorical variables {0,1}.

table(nyc_airbnb$boro)

summary(fit) ## use Bronx as reference

# Take a look at the factors
fit = nyc_airbnb %>% 
    mutate(
        boro = fct_infreq(boro), # fct_infreq(): levels are sorted by frequency ascendingly,
        room_type = fct_infreq(room_type)
    ) %>% 
  lm(price~stars+boro+room_type,data = .) 
fit
table(nyc_airbnb$boro)
table(nyc_airbnb$room_type)
## boro: 以Manhattan为reference，地区变化按照频率rank，Manhattan第一作为参考，其余的三个变量的取值是建立在reference level之上的
```


## see the outcomes

```{r}
coef(fit)[[1]]
fit$coefficients
summary(fit$residuals)
length(fit$residuals)
nyc_airbnb[c(5311,4042),]
fitted.values(fit)[c(4042,5311)] ##？？？
fit %>% broom::glance()
fit %>% broom::tidy()
```


## formula shortcut
```{r}
nyc_airbnb %>% lm(price ~1,data = .) ## intercept only 
nyc_airbnb %>% lm(price ~ 0 + stars,data = .) # no intercept
nyc_airbnb %>% lm(price~.,data = .) # using all as predictors
```


## tidy the results instead using broom::tidy()

the names of the categorical var will be bad in format after lm, so tidy it when showing
```{r}
fit %>% 
    broom::tidy() %>% 
    mutate(term = str_replace(term, "boro","Boro:")) %>% ## change names
    knitr::kable(digits =3 )

```




## diagnostic: modelr

```{r}
## Don't use broom::tidy before when using modelr, for the fit part should be in function form
modelr::add_residuals(nyc_airbnb,fit) %>% 
  ggplot(aes(x = room_type, y = resid)) + 
  geom_violin()+
  ylim(-500,500)

modelr::add_residuals(nyc_airbnb,fit) %>% 
    ggplot(aes(x = boro,y = resid))+
    geom_violin()+
    ylim(-500,500)


modelr::add_residuals(nyc_airbnb,fit) %>% 
    ggplot(aes(x = price,y = resid))+
    geom_point()+
    ylim(-300,500)+
    xlim(0,750)  

## suggesting a clear pattern between y and residuals
## always remember to set the boundaries of plots

modelr::add_predictions(nyc_airbnb,fit) %>% 
  select(price, pred)
## look the residual 
fit_nyc = nyc_airbnb %>% 
  modelr::add_predictions(fit) %>% 
  modelr::add_residuals(fit)
head(fit_nyc)
fit_nyc %>% 
  ggplot(aes(y = resid))+
  geom_boxplot()+
  ylim(-500,500)
  
fit_nyc %>% 
  filter(resid<=0)

```



# interaction

```{r}
fit_interaction = lm(price~stars*boro,data = nyc_airbnb) ## see interaction between stars and boros
fit_interaction %>% 
    broom::tidy()
```

```{r}
fit_interaction2 = lm(price~stars*boro*room_type,data = nyc_airbnb) ## see interaction between stars and boros
fit_interaction2 %>% 
    broom::tidy()

## interprete with respect to reference
```

## nesting 
```{r}
## nest according to boro
nyc_airbnb %>% 
  nest(data = -boro) %>% 
  mutate(
    model = map(.x = data, ~lm(price~stars + room_type, data = .x)),
    model = map(model, broom::tidy)
    ) %>% 
  select(-data) %>% 
  unnest(model) %>% 
  filter(str_detect(term, "^room_")) %>% 
  ggplot(aes(x = boro, y = estimate)) +
  geom_point() +
  facet_grid(.~term)


```



```{r}
## nest in terms of boro.
nest_lm <- 
    nyc_airbnb %>% 
    nest(data = -boro) %>% ## 先把数据按照key nest 起来
    mutate(
        models = map(.x = data, ~lm(price~stars+room_type,data = .x)), ## fit model in different boros
        results = map(models, broom::tidy)
    ) %>% 
    select(boro,results) %>% 
    unnest(results)

table(nyc_airbnb$room_type)
```

```{r}
## nest in terms of neiborhood.
manhattan_nest_ls_res <- 
    nyc_airbnb %>% 
    filter(boro == "Manhattan") %>% 
    nest(data = -neighborhood) %>% ## 先用nest把相关数据分类 
    mutate(
        models = map(.x = data, ~lm(price~stars+room_type,data = .x)), ## fit model in different boros
        results = map(models, broom::tidy)
    ) %>% 
    select(neighborhood,results) %>% 
    unnest(results)


manhattan_nest_ls_res %>% 
    filter(str_detect(term, "room_type")) %>% ## 筛选包含某一字符的列
    ggplot(aes(x = neighborhood, y = estimate)) + 
    geom_point() + 
    facet_grid(~term) + 
    theme(axis.text.x = element_text(angle = 80, hjust = 1))

```




# GLM example
```{r}

```


















